nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["http://localhost:4200"]
        allow_headers: ["Content-Type", "Authorization"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/": null
